; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed= 115200 

; добавка от Толика
; файловая система
board_build.filesystem = littlefs
; разметка областей памяти
board_build.partitions = partitions.csv

build_flags =-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG ; для настройки сообщений debug

lib_deps =
    Links2004/WebSockets @ ^2.6.1

;lib_deps =
;     https://github.com/mischief/arduino-lua.git
;    arduino-libraries/Ethernet @ ^2.0.2
;    khoih-prog/WebServer_ESP32_W5500 @ ^1.5.2
